### ISSUE TITLE
Differences between vsilter, mpv (libass) and xysubfilter with libass

### ISSUE THREAD

**Issue by MatiasMovie** [Masaiki/xy-VSFilter#1]
mpv-x86_64-20210530-git-fd8c673
![image](https://user-images.githubusercontent.com/24187109/121098572-70021900-c7f6-11eb-966a-06fbcad925a0.png)

Player MPC-BE
xyVSFilterSubFilter-pfmod-3.2.0.806
![image](https://user-images.githubusercontent.com/24187109/121098581-74c6cd00-c7f6-11eb-83a3-a68aa09b3d9b.png)

XySubFilter_with_libass_20210605
![image](https://user-images.githubusercontent.com/24187109/121098590-78f2ea80-c7f6-11eb-8563-8195ccaff523.png)

Time in subtitles 3:33
[[VCB-Studio] Kono Subarashii Sekai ni Shukufuku wo! [02][Ma10p_1080p][x265_flac_aac].zip](https://github.com/Masaiki/xy-VSFilter/files/6612443/VCB-Studio.Kono.Subarashii.Sekai.ni.Shukufuku.wo.02.Ma10p_1080p.x265_flac_aac.zip)

I think XySubFilter_with_libass_20210605 is too bright

**Comment by Masaiki** [comment]
Yes, it seems it doesn't handle the color space in a right way.
By the way, the difference between libass and vsfilter can already be said within tolerance.

**Comment by MatiasMovie** [comment]
XySubFilter with libass@5733e1c & directwrite is similar to mpv and xy
![image](https://user-images.githubusercontent.com/24187109/125263533-6727ca00-e303-11eb-89a2-024dc899c2ab.png)

**Comment by Masaiki** [comment]
well, i didn't change the codes about color, so did libass.

**Comment by MatiasMovie** [comment]
xyVSFilterSubFilter-pfmod-3.2.0.806
![image](https://user-images.githubusercontent.com/24187109/150449172-de3c9c27-fd10-415d-a14c-840a333d1fdd.png)

XySubFilter_with_libass_20220110
![image](https://user-images.githubusercontent.com/24187109/150449301-0b9a111d-9b24-45b1-bcf5-a0397fef8313.png)

Subtitles
[[shisha] Seirei Gensouki - 06 [WEB 1080p AAC]_Subtitles01.zip](https://github.com/Masaiki/xy-VSFilter/files/7909652/shisha.Seirei.Gensouki.-.06.WEB.1080p.AAC._Subtitles01.zip)

**Comment by Masaiki** [comment]
> xyVSFilterSubFilter-pfmod-3.2.0.806 ![image](https://user-images.githubusercontent.com/24187109/150449172-de3c9c27-fd10-415d-a14c-840a333d1fdd.png)
> 
> XySubFilter_with_libass_20220110 ![image](https://user-images.githubusercontent.com/24187109/150449301-0b9a111d-9b24-45b1-bcf5-a0397fef8313.png)
> 
> Subtitles [[shisha] Seirei Gensouki - 06 [WEB 1080p AAC]_Subtitles01.zip](https://github.com/Masaiki/xy-VSFilter/files/7909652/shisha.Seirei.Gensouki.-.06.WEB.1080p.AAC._Subtitles01.zip)

A deviation of size 2 was observed under 8-bit RGB.

**Comment by Masaiki** [comment]
https://drive.google.com/file/d/17qcTBkBK1vzJQ1i2sNN7Ztp4iADaDmbn/view?usp=sharing
