### ISSUE TITLE
Position effects bounce in and out of place

### ISSUE THREAD

**Issue by JustNoon** [Masaiki/xy-VSFilter#11]
I don't know what I'm doing or saying so I'm just including as many details as I can think of.

Subtitle position doesn't seem to be set correctly each frame. It is correctly set in mpv or the legacy xy-VSFilter implementation.

Can be convinced to play correctly by 
1. Applying "Use VSFilter (legacy) ASS implementation"
2. Playing at least a frame of video (will render blank otherwise)
3. Seeking backwards to a frame that contains the position effect (citation needed on which exact effect)
4. Unapplying it
This corrects the problem completely until the video is reloaded.

xy-VSFilter with libass
![image](https://user-images.githubusercontent.com/45368472/200182667-7016b626-de1b-40a7-b240-392a5d5017c2.png)

xy-VSFilter
![image](https://user-images.githubusercontent.com/45368472/200182715-ae77b253-80c7-45b4-a4e2-c5cd8fe6c0a3.png)

mpv
![image](https://user-images.githubusercontent.com/45368472/200182770-65613895-10a7-4f69-81a2-f43f1568b4f3.png)

```
{\pos(550.2,841.39)\org(518.6,1025.9)\fscy120\frz-8.67\fry0.89\frx2.78\fnColored Crayons\fs45\c&HA1AFB0&\blur1.5\b}Anime Society\NSpecial Screening
```
`[GJM] Eizouken ni wa Te wo Dasu na! - 01 [E3DDFF5F].mkv 07:16.87`
`MPC-HC 1.9.7` `madVR 0.92.17` `XySubFilter with libass version 20220831`

**Comment by Masaiki** [comment]
i can't reproduce it using mpc-be 1.6.4 / mpc-hc 1.9.23 / mpc-hc 1.9.7 + mpcvr/madVR + XySubFilter with libass version 20220831

**Comment by JustNoon** [comment]
It working for you made me believe it must be a setting so I investigated after updating to mpc-hc 1.9.23

I've learned that `Allow video renderer to reposition simple SSA/ASS subtiles` being checked causes the issue for me. Unchecking it fixes it completely as far as I can tell.

Whether the difference between checked and unchecked is a bug that warranted this issue being open is left to your discretion I suppose. I'm not entirely sure the intended behavior of the checkbox anyways but for my purposes, the issue is as good as fixed.

Thanks for your help!

**Comment by Masaiki** [comment]
it might be a madVR setting
process.zoom control.move subtitles -> to bottom of the screen/window

**Comment by JustNoon** [comment]
You're definitely right. Unchecking that fixes it. The culprit has been found!

**Comment by Masaiki** [comment]
fixed by https://github.com/Masaiki/xy-VSFilter/commit/039503ea8862998c30b0ed1c30ec3bfb6afa06f0
