### ISSUE TITLE
Force Default Subtitles error on version 20221208

### ISSUE THREAD

**Issue by Fergdog** [Masaiki/xy-VSFilter#12]
I'm able to turn force default on while a video is playing BUT turning force default off while a video is playing does nothing. I have to close and reopen a video for turning force default off to work.

**Comment by Masaiki** [comment]
[20221216.zip](https://github.com/Masaiki/xy-VSFilter/files/10247048/20221216.zip)
I tried to solve the problem, you can try this build

**Comment by Fergdog** [comment]
Thanks! That fixed it.

**Comment by Masaiki** [comment]
fixed by https://github.com/Masaiki/xy-VSFilter/commit/0cc0c9e76865168888e2764fc5ebaa350e9eb605
