### ISSUE TITLE
Failed to load subtitle file

### ISSUE THREAD

**Issue by Hqndler** [Masaiki/xy-VSFilter#13]
When drag and droping a subtitle file this message pops and the external subtitle isn't loaded... 
Also I had to reinstall mpc to be able to test with the regular xy-vsfilter. After uninstalling your version the regular one is unavaible. (might be another issue).

**Comment by clsid2** [comment]
You need latest development build of MPC-HC. Older versions only support drag&drop for its internal subtitle renderer.

**Comment by Hqndler** [comment]
Maybe I was using the internal render the whole time before testing this (don't remember tbh), since I wanted to test with the regular xy-vsfilter I also updated mpc from whatever version (I didn't recall the version but I didn't updated in a while) to the latest k-lite build with mpc version 2.0.0.16, witch is a dev build. I didn't thought that k-lite pack would include dev built so I think that's what mislead me, and maybe it's an unfair issue.

Anyway the second remark is still valid.

**Comment by clsid2** [comment]
If you uninstalled these filters, then you need to re-register the other ones. They share the same GUID.

**Comment by Hqndler** [comment]
So there's a missing line in the Unistall_XySubFilter.bat to re-register the old filter.

**Comment by clsid2** [comment]
No, that is your own job.

**Comment by Hqndler** [comment]
I hope that no one will want to go back to the basic version and will not have this problem, for me it could be fixed by masaiki since the installation is one click, the uninstallation could restore the basic parameters in one click too...
