### ISSUE TITLE
无法在MPC-HC中切换外挂字幕轨 (Cannot switch between external subtitle tracks in MPC-HC)

### ISSUE THREAD

**Issue by SnowMist126** [Masaiki/xy-VSFilter#16]
问题简述：在MPC-HC中使用XySubFilter作为字幕渲染器后，能加载外挂字幕并正常渲染到画面中，但是MPC-HC中「字幕轨」选项为灰色（这通常表示没有载入的字幕轨），也无法使用字幕轨相关快捷键。
![20230604_000713_580](https://github.com/Masaiki/xy-VSFilter/assets/12470940/048b960e-44f5-40d3-ac8f-b943f51b1321)

已经尝试的方案：
1.更换字幕渲染器：
MPC-HC的「选项-回放-输出-字幕渲染器」设置为「内部字幕渲染器」，重新打开视频。可以显示已载入的外挂字幕。如下图。
![20230604_000846_650_mpc-hc64](https://github.com/Masaiki/xy-VSFilter/assets/12470940/1528a1bd-9ddc-48c0-a113-a3881a21b75d)
2.重新安装XySubFilter：
2.1.接着以管理员身份运行 D:\Program Files\XySubFilter_with_libass_20230505\x64\Uninstall_XySubFilter.bat ，显示操作成功。重新打开视频，在MPC-HC的选项中可以看见XySubFilter后面写着不可用。
2.2接着以管理员身份运行 D:\Program Files\XySubFilter_with_libass_20230505\x64\Install_XySubFilter.bat ，显示操作成功。重新打开视频，在MPC-HC的选项中可以看见XySubFilter可用。
2.3MPC-HC的「选项-回放-输出-字幕渲染器」设置为「XySubFilter」，重新打开视频。不能显示已载入的外挂字幕。

配置：
系统：Windows10 64位
播放器：MPC-HC (Nightly 64bit) 2.0.0.45 - 下载自https://codecguide.com/download_k-lite_codec_pack_full.htm
XySubFilter：XySubFilter_with_libass_20230505\x64
配置方案：https://vcb-s.com/archives/16609

**Comment by SnowMist126** [comment]
播放文件：[雪飘工作室][海阔天空！光之美少女/Hirogaru_Sky！Precure/ひろがるスカイ！プリキュア][WEBDL][1080p][17][简繁外挂]
文件页面：https://share.dmhy.org/topics/view/641478_Hirogaru_Sky_Precure_WEBDL_1080p_17_Q.html
磁力链接：magnet:?xt=urn:btih:4EVGKCR7CZT6BB6YANSA2OSN4V7BS5RU

**Comment by Masaiki** [comment]
大概测试了一下 支持切换内封字幕的字幕轨 不支持切换外挂字幕
这个是 mpc-hc 没有适配的结果，在[原版](https://github.com/Cyberbeing/xy-VSFilter)同样存在，建议到 [mpc-hc](https://github.com/clsid2/mpc-hc) 那里提交 issue，这里也会保留这个 issue 直到 mpc-hc 那边适配

**Comment by clsid2** [comment]
MPC-HC uses IAMStreamSelect interface to query track information. You have not got that implemented correctly.
For subtitle use `dwGroup` value 2.

Also, when there is only external subs, XySubFilter only load if I set it to load always. It should also work when load is set to when needed.

**Comment by Masaiki** [comment]
@clsid2 As far as I'm concerned, using `get_LanguageCount` `get_LanguageName` `get_SelectedLanguage` `put_SelectedLanguage` in IDirectVobSub to implement subtitle selection would be better, am i right?

**Comment by clsid2** [comment]
IAMStreamSelect is a generic interface that works with all DirectShow players.

Expose the external subtitle tracks there. The embedded ones are already handled by the splitter.

**Comment by SnowMist126** [comment]
请问我还需要在MPC-HC那里提交bug吗？还是说我等待XySubFilter之后的更新就可以了？ @Masaiki

**Comment by pkuislm** [comment]
VSFilter好像也有这个问题（即只能列出内置字幕，但却可以加载外置字幕。但若加载了外置字幕，即使在字幕轨中手动调整也无法切换轨道了。我感觉是不是跟选中的轨道Index还是啥有关系？）。我怀疑这个问题是不是从VSFilter那里“继承”来的
Actually, VSFilter seems to have the same problem which can only list out embedded subtitles even if external subtitles can be loaded. I wonder if it's "inherited" from VSFilter?

**Comment by Masaiki** [comment]
resolved by https://github.com/Masaiki/xy-VSFilter/pull/22
