### ISSUE TITLE
xysubfilter vs xysubfilter with libass

### ISSUE THREAD

**Issue by MatiasMovie** [Masaiki/xy-VSFilter#2]
xysubfilter with libass
![image](https://user-images.githubusercontent.com/24187109/121099003-557c6f80-c7f7-11eb-9360-9ddc0360708c.png)

xysubfilter
![image](https://user-images.githubusercontent.com/24187109/121099041-69c06c80-c7f7-11eb-9401-8c761733a0d9.png)

I think it's same problem as
https://github.com/libass/libass/issues/509

**Comment by Masaiki** [comment]
this pr https://github.com/libass/libass/pull/511 aims to fix it.
xysubfilter_with_libass will always use the latest released libass.

**Comment by MatiasMovie** [comment]
XySubFilter with libass@5733e1c & directwrite
![image](https://user-images.githubusercontent.com/24187109/125263890-af46ec80-e303-11eb-87be-4080f1302ab3.png)
