### ISSUE TITLE
Incompatible with CrystalDiskInfo which is using MCI | 与CrystalDiskInfo（使用了MCI）不兼容

### ISSUE THREAD

**Issue by DogTorrent** [Masaiki/xy-VSFilter#23]
CrystalDiskInfo只要一播放声音（点击小人或者挂后台警告）就会crash，我拖了cdi的源码下来debug，发现CrystalDiskInfo使用了MCI并指定了lpstrDeviceType=MPEGVideo的方式来播放wav音频，进而会用到mciqtz32.dll里的方法（HKLM\Software\Microsoft\Windows NT\CurrentVersion\MCI32里指定了MPEGVideo使用mciqtz32.dll），而mciqtz32.dll似乎又会去使用系统上安装的DirectShow滤镜，然后就导致了崩溃。
我这里检查发现32位的XySubFilter.dll会导致32位的CrystalDiskInfo崩溃，64位的XySubFilter.dll会导致64位的CrystalDiskInfo崩溃，而使用K-Lite带的XySubFilter.dll则不会导致崩溃，大概确实应该是XySubFilter_with_libass引入的问题？

**Comment by Masaiki** [comment]
啊？这有点怪，我周末看看

**Comment by Masaiki** [comment]
@DogTorrent 
我发现不只是 XySubFilter_with_libass 其他版本 https://github.com/Cyberbeing/xy-VSFilter & https://github.com/pinterf/xy-VSFilter 也存在这个问题
klite 中可能用的是 potplayer 添加的全局滤镜？没注册这个 dll 所以避免了这一问题？我暂时不太清楚
我尝试性的修了一下 本地测试已经通过你可以试一下
[test_build.zip](https://github.com/Masaiki/xy-VSFilter/files/15283443/test_build.zip)

**Comment by DogTorrent** [comment]
> @DogTorrent 我发现不只是 XySubFilter_with_libass 其他版本 https://github.com/Cyberbeing/xy-VSFilter & https://github.com/pinterf/xy-VSFilter 也存在这个问题 klite 中可能用的是 potplayer 添加的全局滤镜？没注册这个 dll 所以避免了这一问题？我暂时不太清楚 我尝试性的修了一下 本地测试已经通过你可以试一下 [test_build.zip](https://github.com/Masaiki/xy-VSFilter/files/15283443/test_build.zip)

新的我测了下，没有问题了。
[Cyberbeing/xy-VSFilter](https://github.com/Cyberbeing/xy-VSFilter)的3.1.0.752和[pinterf/xy-VSFilter](https://github.com/pinterf/xy-VSFilter)的3.2.0.810、3.2.0.806我也都试了，确实都会导致崩溃。但是k-lite带的的dll（版本号为3.2.0.806）我手动注册后也还是正常的，看起来并不是没有注册的问题，也不知道k-lite带的dll是哪来的
