### ISSUE TITLE
Subtitle Track List Display Broken in MPC-BE

### ISSUE THREAD

**Issue by lahhn** [Masaiki/xy-VSFilter#24]
The changes to fix subtitle track list display for MPC-HC may have unfortunately broken subtitle track list display in MPC-BE.
I'm using the most recent version of MPC-BEx64 1.7.2 (June 7, 2024), the issue was also present on an MPC-BE version from several months ago before updating.
The previous release [XySubFilter with libass version 20230505] still displays the subtitle track list without issue for MPC-BE.

![Screenshot 2024-06-09 190947](https://github.com/Masaiki/xy-VSFilter/assets/38773571/0dc7b035-d539-4c31-b5f0-b51cbc84c6d1)

**Comment by Masaiki** [comment]
Noticed, thanks for reporting.

**Comment by Masaiki** [comment]
fixed in https://github.com/Masaiki/xy-VSFilter/commit/63d1a944c7b6bdaec095501aa2060a50cf2f24c3
test build: https://github.com/Masaiki/xy-VSFilter/actions/runs/9440986492
