### ISSUE TITLE
mpv vs xysubfilter with libass

### ISSUE THREAD

**Issue by MatiasMovie** [Masaiki/xy-VSFilter#3]
5min22sec

mpv
![image](https://user-images.githubusercontent.com/24187109/124399005-14ee1400-dd19-11eb-8934-ffff1e92f0d4.png)

xysubfilter with libass
![image](https://user-images.githubusercontent.com/24187109/124399016-20d9d600-dd19-11eb-9ece-b15d67eb2403.png)

Subs
[[VCB-Studio] Kono Subarashii Sekai ni Shukufuku wo! [02][Ma10p_1080p][x265_flac_aac].zip](https://github.com/Masaiki/xy-VSFilter/files/6760561/VCB-Studio.Kono.Subarashii.Sekai.ni.Shukufuku.wo.02.Ma10p_1080p.x265_flac_aac.zip)

**Comment by Masaiki** [comment]
Try [this](https://drive.google.com/file/d/1TJ7pV17CJDlodgafPXewVJ4wx-e9SHpp/view?usp=sharing), this uses fontconfig instead of directwrite.

**Comment by MatiasMovie** [comment]
Two problems:
-Slow start in mpc-hc/be
-MPC-BE generate two files when start video

**Comment by Masaiki** [comment]
> Two problems:
> -Slow start in mpc-hc/be
> -MPC-BE generate two files when start video

Two files? Can you be more specific?

**Comment by Masaiki** [comment]
[XySubFilter with libass@5733e1c & directwrite](https://drive.google.com/file/d/1eYHF1Fcedze9AX9rL3RFlKl_LdGCDZhI/view?usp=sharing)
seems good too. So just wait for libass 0.15.2

**Comment by MatiasMovie** [comment]
Works fine, thx :)
