### ISSUE TITLE
Crash when watching

### ISSUE THREAD

**Issue by MatiasMovie** [Masaiki/xy-VSFilter#4]
I have render crash when watching this 
[[VCB-Studio] Kono Subarashii Sekai ni Shukufuku wo! [02][Ma10p_1080p][x265_flac_aac].zip](https://github.com/Masaiki/xy-VSFilter/files/7164323/VCB-Studio.Kono.Subarashii.Sekai.ni.Shukufuku.wo.02.Ma10p_1080p.x265_flac_aac.zip)
crash between 1:57 and 3:27

XySubFilter with libass@5733e1c & directwrite works fine

**Comment by Masaiki** [comment]
i test it with mpc-be 1.5.8 x64, and nothing happened.

**Comment by MatiasMovie** [comment]
I have MPC-BE 1.5.8.6302 + madvr beta 140 + external codecs (K-lite full)

**Comment by Masaiki** [comment]
Maybe more infomation is needed to reproduce the possible problem.

**Comment by MatiasMovie** [comment]
I do not know what information I could give
I'm playing video
skip to 1:57 and watch, and I have info subtitle renderer crashed on left corner
![image](https://user-images.githubusercontent.com/24187109/133414967-8298e1d5-4810-4bd1-8e1b-f66fc33eb334.png)


[madvr beta 140](http://madshi.net/madVRhdrMeasure140.zip)

**Comment by Masaiki** [comment]
test with madvr beta 140, still nothing happened.
here is a re-compiled one, https://drive.google.com/file/d/1Rt-B9V31ltmr2_Wf3MQuI3PEHoR35DmO/view?usp=sharing

**Comment by MatiasMovie** [comment]
I test with stable madvr and internal codesd and still crash

**Comment by Masaiki** [comment]
While testing another library that uses Libass, I found that the latest freetype release may have problems with certain fonts. This version reverses FreeType to the previous version.
https://drive.google.com/file/d/1QX8xKbVCkhrq73c3iVd9ILAmBngpWODs/view?usp=sharing

**Comment by MatiasMovie** [comment]
Now work good 👌
