### ISSUE TITLE
Font of ASS

### ISSUE THREAD

**Issue by GYQ-18** [Masaiki/xy-VSFilter#5]
It cant change the font of ass subtitles, but it works right with SRT

**Comment by Masaiki** [comment]
test build: https://drive.google.com/file/d/1CIEl4G1NSVaXeK-knzBImQGqbuB6xQlY/view?usp=sharing

**Comment by GYQ-18** [comment]
> test build: https://drive.google.com/file/d/1CIEl4G1NSVaXeK-knzBImQGqbuB6xQlY/view?usp=sharing

in this version, if i use the "default" tab to change its font, it does work; but it won't work using the "global default" tab.
![image](https://user-images.githubusercontent.com/69042092/156294621-84bcc3bb-28c3-4f70-a718-26042865d20c.png)
![image](https://user-images.githubusercontent.com/69042092/156294671-f182a5a3-443e-45fd-b3a9-c5decf6466e0.png)

**Comment by Masaiki** [comment]
global default is mainly for srt and lost styles.
to edit it is quite difficult, so it still use xy-VSFilter itself to render srt

**Comment by xLn2** [comment]
It would be nice to see global default (or player default) override substation alfa subtitles default's. At the time default style resets by opening another video and it's quite annoying.

**Comment by Masaiki** [comment]
> It would be nice to see global default (or player default) override substation alfa subtitles default's. At the time default style resets by opening another video and it's quite annoying.

now Force Default works, but closing it will take effects in the next start
[XySubFilter_80d1357.zip](https://github.com/Masaiki/xy-VSFilter/files/9076014/XySubFilter_80d1357.zip)
