### ISSUE TITLE
Old subtitles remain after selecting new subtitles

### ISSUE THREAD

**Issue by v0lt** [Masaiki/xy-VSFilter#6]
After selecting other subtitles, the text of the old subtitles **sometimes** continues to be displayed until the text of the new subtitles appears.
This can be seen when there are subtitles with and without lyrics.

I give [a link to the sample.](https://www.sendspace.com/file/8e0vf9) Start playback, select karaoke subtitles first, and then external subtitles.

**Comment by Masaiki** [comment]
Known problem, previously felt that the impact is minor so it has been not touched
Will be figured recently.

**Comment by Masaiki** [comment]
A [test build](https://drive.google.com/file/d/1uXtGO48qxKKIg_vE93W8ufXQF3hu72OH/view?usp=sharing) for this

**Comment by v0lt** [comment]
The test build seems to work correctly.

**Comment by Masaiki** [comment]
fixed by https://github.com/Masaiki/xy-VSFilter/commit/c9a683b2c6a44ef92a918272ee698c401f1a0478
