### ISSUE TITLE
subtitle timing cause disappearance of sub

### ISSUE THREAD

**Issue by xLn2** [Masaiki/xy-VSFilter#7]
I am using Mpc-hc 1.9.21.30, with your latest xy-VSFilter.
When I use mpc-hc's own sub shift key (F1-F2) cause to the movie subtitle (embedded .ass format) disappears. I tried with filters own shifting setting but I face same result. I haven't tested what the subtitle sizing and shifting placement settings will lead to.

also other things might be considered as bug : 

- filter does not detect player's Default track preferance, so I have to edit internal lav splitter.

![resim](https://user-images.githubusercontent.com/3073922/171910118-918480a8-1ede-44c4-a267-ecdadef8a988.png)

- drag and drop subtitle does not work on mpc-hc with xy-VSFilter

- mpc-hc status bar does not show sub language with xy-VSFilter (player got update about it. It is 4 letter regional language code probably, I do not know much)

![resim](https://user-images.githubusercontent.com/3073922/171913048-99875b80-52f6-4e49-a0e2-24b90e863529.png) ![resim](https://user-images.githubusercontent.com/3073922/171912854-2a275c9a-cfd3-4980-871a-cec634b07ef5.png)     
![resim](https://user-images.githubusercontent.com/3073922/171913133-9740a959-573e-476e-a458-0b879e42933b.png) ![resim](https://user-images.githubusercontent.com/3073922/171912795-34526700-dcae-4014-a23e-e7e5e9c7c172.png)

Thanks.

**Comment by Masaiki** [comment]
I tried some fixes in https://github.com/Masaiki/xy-VSFilter/commit/43b6a0337172f79a090b8280dde5229f7b86314c. Now there should be no problem setting delay and speed in the filter UI, but it still behaves strangely through the player shortcuts.
Here is a test build [XySubFilter_43b6a03.zip](https://github.com/Masaiki/xy-VSFilter/files/9075652/XySubFilter_43b6a03.zip)
