### ISSUE TITLE
An error when playing SUP Subtitles

### ISSUE THREAD

**Issue by Lambholl** [Masaiki/xy-VSFilter#8]
When playing SUP subtitles (PGS), the time axis is not correct. And with the video play on, the deviation increases. But this does not happen when playing PGS subtitles which are packed in the videos. (Tested on framerate 24000/1001)

播放SUP封装的PGS外挂图形字幕时，存在字幕时间轴与视频时间不对应的情况；并且随着播放时间的增加，时间轴偏差的越来越多。但是在播放PGS内封字幕时，并没有这个bug。(测试视频帧率为24000/1001)

**Comment by Masaiki** [comment]
[XySubFilter_20220828.zip](https://github.com/Masaiki/xy-VSFilter/files/9439428/XySubFilter_20220828.zip)
try this
试一下这个

**Comment by Lambholl** [comment]
还是一样的bug




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Masaiki/xy-VSFilter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月28日(星期天) 晚上6:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Masaiki/xy-VSFilter] An error when playing SUP Subtitles (Issue #8)





 
XySubFilter_20220828.zip
 try this
 试一下这个

**Comment by Masaiki** [comment]
fixed by https://github.com/Masaiki/xy-VSFilter/commit/6a4a14663ac3a5b5f38e523451158af2607c2838
