### ISSUE TITLE
Discuss: how to best signal this isn't actual xy-VSFilter

### ISSUE THREAD

**Issue by TheOneric** [Masaiki/xy-VSFilter#9]
I recall encountering several instances where bug reporters, confused or improperly labeled "xy-VSFIler/SUbFilter with libass" as plain "xy-VSFilter/SubFilter" *(though without taking a closer look again I can only refer to one report immediately)*.
So, I was wondering if it’d be possible to make it even more obvious that what can be found here is only using the VSFIlter/SubFilter interface but a completely different (unfortunately) not (yet) fully compatible implementation. Currently, `README.md` and the Release notes already mention that this is “with libass”, but perhaps this and its meaning could be conveyed even more prominently. I was thinking of some or all of the following, though different approach certainly can work too:

 - don't just refer to “with libass” in `README.md` and release notes. Explicitly state, that the backend is *replaced* by libass, keeping only the interface, and that compatibility issues with original xy-VSFilter/SubFillter may arise.

 - The `About` section at the top right of the repo’s default page (`Code`) still refers to the “Official xy-VSFilter Repository”, which may also be mistaken on a cursory glance as this *being* the official repo. This could be changed to a description specific to this repo, e.g. *“libass wrapped in an xy-VSFilter/xy-SubFilter interface”*.

 - perhaps also change the name of the repo to `xy-VSFilter-with-libass` or something similar. This will automatically create a redirection for all `Masaiki/xy-VSFilter/*` links to `Masaiki/<new name>/*`. The redirection will afaik remain in place unless you create a new repo named `xy-VSFilter`. 

It’s possible it’s already plenty clear enough and the reporters just forgot about this not being actual xy-VSFilter some time after downloading, but I figured it is worth to at least ask.

**Comment by Masaiki** [comment]
I basically agree with the first two proposals, and regarding the third proposal, I will consider it when more changes are made to the project.

**Comment by TheOneric** [comment]
Thanks, the changes made should (hopefully) help clear things up!
Imho it would also be good to edit the text of the last release on GitHub, to ensure people who are directly navigating to https://github.com/Masaiki/xy-VSFilter/releases/latest also get to see an explicit note about xy-VSFilter incompatibility. I’m thinking even something short like e.g. the following should do:
 &nbsp;&nbsp; “**Note:** This uses *libass* to render ASS and SSA, so the rendering of those is not compatible with original xy-VSFilter!”

----

**EDIT:** the new release's description now has such a notice, thanks!
